#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>
#include "scene.hpp"
#include "light.hpp"
#include "sphere.hpp"
#include "box.hpp"
